import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <title>Via Appia SOS Rodovias</title>
        <link rel="icon" href="/icon-via.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-grow mx-auto max-w-7xl px-4">{children}</div>

        <footer className="text-center py-4 bg-gray-400 w-full text-white">
          <p>&copy; 2025 Via Appia. Todos os direitos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
